In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
data = {'area': [2600, 3000,3200,3600,4000], 'bedroom': [3, 4, np.nan,3,5], 'age':[20,15,18,30,8] , 'price':[550000,565000, 610000, 595000, 760000]}
df = pd.DataFrame(data)
df.infer_objects()
df


area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [3]:
df.bedroom.median()

3.5

In [4]:
import math
median_bedrooms = math.floor(df.bedroom.median())
median_bedrooms

3

In [5]:
df.bedroom = df.bedroom.fillna(median_bedrooms)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedroom','age']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [8]:
reg.intercept_

383724.99999999994

In [9]:
reg.predict([[3000,3,40]])

array([444400.])

In [10]:
137.25 * 3000 + -26025*3 + -6825*40 + 383724.99999999994


444399.99999999994

In [11]:
reg.predict([[2500,4,5]])

array([588625.])

In [12]:
data = {'experience': [np.nan,np.nan,'five','two','seven','three','ten','eleven'], 'test_score(out of 10)': [8,8,6,10,9,7,np.nan, 7], 'interview_score(out of 10)':[9,6,7,10,6,10,7,8] , 'salary($)':[50000,45000, 60000, 65000, 70000,62000,72000,80000]}
df = pd.DataFrame(data)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
df.experience = df.experience.apply(w2n.word_to_num)
df

NameError: name 'w2n' is not defined